Добавление функции бронирования
AlexanderSobko/java-shareit pull request #4
Opened 2023-06-06 07:57 UTC by AlexanderSobko

feat: реализовал функцию бронирования согласно ТЗ
feat: реализовал функцию добавления отзывов для предметов согласно ТЗ

2023-06-06 13:58 UTC, NikolaiDem requested changes

2023-06-06 13:58 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImp.java
> +        item.setNextBooking(getNextBooking(item.getId()));
Проблема N+1 запроса. Необходимо избавиться от обращения к БД при итерировании по каждому item-у (при получении последнего и следующего бронирований). Допустимо делать несколько запросов, но для всего списка item-ов сразу. Например, одним запросом получить все последние бронирования для списка item-ов. Еще одним одним запросом получить все следующие бронирования и тд. Но не обращаться по каждому item-у в БД

2023-06-06 13:58 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImp.java
> +            Predicate byStart = cb.lessThan(root.get("start"), cb.currentTimestamp());
Лучше, чтобы бронирование было завершено к моменту написания комментария

2023-06-06 13:58 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImp.java
> +    public List<Item> getItems(long userId) {
Добавить комментарии в ответ в соответствии с ТЗ и удалить их из Item:

Отзывы можно будет увидеть по двум эндпоинтам — по GET /items/{itemId} для одной конкретной вещи и по GET /items для всех вещей данного пользователя.

2023-06-06 13:58 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +        validateItem(item);
Еще лучше проверить, что вещь не забронирована никем другим на запрашиваемые даты.

2023-06-06 13:58 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +        }
И можно проверить, что бронирование еще началось

2023-06-06 13:58 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public ResponseEntity<Booking> saveBooking(@RequestBody @Valid BookingCreationDto dto,
Для общения с внешним миром лучше использовать dto, а не доменные объекты. Например, для того чтобы избежать изменения клиента при изменении структуры БД.
Аналогично для всех методов и других контроллеров.

2023-06-06 13:58 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    @OneToMany(fetch = FetchType.EAGER, mappedBy = "item", cascade = CascadeType.REMOVE)
OneToMany создает N+1 query issue.
https://vladmihalcea.com/n-plus-1-query-problem/
Лучше получать комментарии в сервисе отдельно

2023-06-07 04:45 UTC, AlexanderSobko commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImp.java
> +            Predicate byStart = cb.lessThan(root.get("start"), cb.currentTimestamp());
Сделал так из-за тестов, почемуто не проходит по другому(

2023-06-07 14:36 UTC, AlexanderSobko commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public ResponseEntity<Booking> saveBooking(@RequestBody @Valid BookingCreationDto dto,
Исправил

2023-06-07 14:40 UTC, AlexanderSobko commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImp.java
> +            Predicate byStart = cb.lessThan(root.get("start"), cb.currentTimestamp());
> Сделал так из-за тестов, почемуто не проходит по другому(

Исправил

2023-06-08 06:42 UTC, AlexanderSobko commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImp.java
> +        item.setNextBooking(getNextBooking(item.getId()));
Исправил

2023-06-08 06:50 UTC, AlexanderSobko commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +        }
Исправил

2023-06-09 03:33 UTC, AlexanderSobko commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    @OneToMany(fetch = FetchType.EAGER, mappedBy = "item", cascade = CascadeType.REMOVE)
Судя по логам, там нет n+1 проблемы по крайней мере не с комментами, они выгружаются одним запросом через join, но возможно они не нужны в составе Booking? Но если делать отдельный вызов в сервисе, то это же и будет дополнительный запрос

2023-06-09 10:24 UTC, AlexanderSobko commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImp.java
> +    public List<Item> getItems(long userId) {
Вроде исправил =)

2023-06-10 08:05 UTC, AlexanderSobko commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +        validateItem(item);
Добавил, но она ломает тесты(

2023-06-11 08:01 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImp.java
> +                    lastBookings.stream()
Чтобы избавиться от вложенной итерации по lastBookings, лучше преобразовать lastBookings в мапу, где ключ - itemId, а значение - список бронирований по itemId. Тогда бронирования можно получать за константное время.
Аналогично для nextBookings

2023-06-11 08:01 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +    private void validateTime(Booking booking) {
Какие тесты ломаются?

2023-06-11 08:01 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    @OneToMany(fetch = FetchType.EAGER, mappedBy = "item", cascade = CascadeType.REMOVE)
Сейчас с join fetch ок. Но необходимо тогда убрать комментарии в маппинге при поиске (/search), так как они создают дополнительные запроса. И по ТЗ они там не нужны

2023-06-11 08:03 UTC, NikolaiDem requested changes
Александр, необходимо избавиться от вложенного стрима

2023-06-12 06:16 UTC, AlexanderSobko commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    @OneToMany(fetch = FetchType.EAGER, mappedBy = "item", cascade = CascadeType.REMOVE)
Исправил

2023-06-12 06:16 UTC, AlexanderSobko commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImp.java
> +                    lastBookings.stream()
Исправил

2023-06-12 06:43 UTC, AlexanderSobko commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +    private void validateTime(Booking booking) {
Исправил

2023-06-12 10:29 UTC, NikolaiDem approved these changes

2023-06-13 09:14 UTC, merged