Добавить функционал запросов согласно ТЗ
AlexanderSobko/java-shareit pull request #5
Opened 2023-06-14 12:20 UTC by AlexanderSobko

feat: добавил пагинацию  в эндпоинты GET /items, GET /items/search, GET /bookings и GET /bookings/owner

2023-06-17 00:34 UTC, NikolaiDem requested changes

2023-06-17 00:34 UTC, NikolaiDem commented on pom.xml
> +<!--		<profile>-->
Почему закомментирован?

2023-06-17 00:34 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    private void validateFromAndSize(long from, int size) {
Вместо кастомной валидации можно использовать constraint annotations - Positive и PositiveOrZero

2023-06-17 00:34 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +                .skip(from)
Вместо sortByDateAsc лучше использовать Pageable. Тогда не придется добавлять skip и limit

2023-06-17 00:34 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    private void validateFromAndSize(long from, int size) {
Вместо кастомной валидации можно использовать constraint annotations - Positive и PositiveOrZero

2023-06-17 00:34 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImp.java
>          List<Item> items = itemRepo.findAll(withNameOrDescriptionSource(text));
Лучше добавить 2ой аргумент Pageable, тогда не придется использовать skip и limit.
Аналогично для getItems(...)

2023-06-17 00:34 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +    private void validateFromAndSize(long from, int size) {
Вместо кастомной валидации можно использовать constraint annotations - Positive и PositiveOrZero

2023-06-17 00:34 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImp.java
> +                .skip(from)
skip и limit заменить на Pageable

2023-06-17 00:34 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/ItemRequestRepository.java
> +    List<ItemRequest> findAllByUser(User user);
Чтобы не было проблемы N+1, лучше добавить join fetch.
Аналогично для findAllByUserNot(...)

2023-06-17 00:34 UTC, NikolaiDem commented on src/test/java/ru/practicum/shareit/ShareItTests.java
>  class ShareItTests {
Отсутствуют тесты unit, репозиториев и контроллеров. 
Интеграционные тесты - это хорошо, но в соответствии с пирамидой тестирования всё не должно ограничиваться только ими )

2023-06-25 06:29 UTC, AlexanderSobko commented on src/main/java/ru/practicum/shareit/request/ItemRequestRepository.java
> +    List<ItemRequest> findAllByUser(User user);
У модели "ItemRequest" у полей user и items fetch = FetchType.EAGER

2023-06-25 06:37 UTC, AlexanderSobko commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImp.java
> +                .skip(from)
Честно, не знаю как сделат LIMIT и OFFSET с помощю PageRequest. Видел вариант с написанием кастомного класса от Pageble, но так и не разобрался как он работает(

2023-06-29 17:58 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/ItemRequestRepository.java
> +    List<ItemRequest> findAllByUser(User user);
Но запросов все равно много) Лучше в сервисе найти items сразу для всех itemRequests

2023-06-29 18:03 UTC, NikolaiDem commented on src/test/java/ru/practicum/shareit/ShareItTests.java
>  class ShareItTests {
Не исправлено

2023-06-29 18:04 UTC, NikolaiDem requested changes
Александр, необходимо исправить оставшиеся замечания)

2023-07-02 17:14 UTC, NikolaiDem approved these changes

2023-07-02 17:14 UTC, NikolaiDem commented on pom.xml
> +			<version>5.0.0</version>
И scope test

2023-07-03 05:40 UTC, merged